services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - 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
    ports:
      - "8000:8000"

  mongodb:
    image: mongodb/mongodb-community-server:6.0.6-ubuntu2204
    ports:
      - "8001:8001"
  qdrant:
    image: qdrant/qdrant
    ports:
      - "8002:8002"
  clearml:
    image: allegroai/clearml
    ports:
      - "8003:8003"

    